### ISSUE TITLE
Error: EINVAL, invalid argument (Updated with demo code for RPI)

### ISSUE THREAD

**Issue by KyleKing** [jantimon/meteor-gpio#2]
Hi, I'm having trouble configuring the demo.

I'm on a RPI2 with a fresh installation of Raspbian (Jessie). I'm able to run meteor and tested the sample todos app. I followed the workaround to include jantimon:meteor-gpio as a private package and am able to run meteor, but I get this error:

```
=> Exited with code: 8
W20151006-14:35:19.803(-4)? (STDERR) Error: EINVAL, invalid argument
W20151006-14:35:19.805(-4)? (STDERR)     at Object.fs.writeSync (fs.js:540:18)
W20151006-14:35:19.806(-4)? (STDERR)     at Object.fs.writeFileSync (fs.js:987:21)
W20151006-14:35:19.808(-4)? (STDERR)     at new Gpio (/home/pi/GPIO-test/.meteor/local/isopacks/jantimon_gpio/npm/node_modules/onoff/onoff.js:82:8)
W20151006-14:35:19.811(-4)? (STDERR)     at Object.gpio.getPort (packages/jantimon_gpio/server/index.js:61:1)
W20151006-14:35:19.812(-4)? (STDERR)     at packages/jantimon_gpio/server/index.js:25:1
W20151006-14:35:19.813(-4)? (STDERR)     at Array.forEach (packages/es5-shim/.npm/package/node_modules/es5-shim/es5-shim.js:417:1)
W20151006-14:35:19.815(-4)? (STDERR)     at Object.gpio.configure (packages/jantimon_gpio/server/index.js:23:1)
W20151006-14:35:19.816(-4)? (STDERR)     at GPIO-test.js:32:8
W20151006-14:35:19.817(-4)? (STDERR)     at /home/pi/GPIO-test/.meteor/local/build/programs/server/app/GPIO-test.js:69:4
W20151006-14:35:19.819(-4)? (STDERR)     at /home/pi/GPIO-test/.meteor/local/build/programs/server/boot.js:242:10
```

I'm using the demo code and this is the function that causes and issue:

```
  // Configuration
  if (Meteor.isServer) {
    gpio.configure({
      poll: true,
      publish: true,
      ports: {
        104: 'out',
        102: 'out',
        97: 'out',
        101: 'out',
        83: 'out',
        88: 'out',
        108: 'in'
      }
    });
  }
```

Have you seen this error before? I have to go to class now, but I will update my question with more information later tonight.

Edit: I think the pin numbers might be the issue...woops!

**Comment by KyleKing** [comment]
Yep, I just needed to test it. There is definitely not a pin 104 on the RPI...or 102 for that matter.

While I was at it, I modified the basic example to work with this package. If you run ``meteor create helloworld` replace helloworld.js and helloworld.html with the following files:

[And don't forget the meteor package, which is tricky, but follow this [guide](https://github.com/jantimon/meteor-gpio/issues/1)]

``` JS
// helloworld.js
GPIOData = new Meteor.Collection('gpio');

// Configuration
if (Meteor.isServer) {
  gpio.configure({
    poll: true,
    publish: true,
    ports: {
      26: 'out',
      19: 'in'
    }
  });

  // Turn LED on from server
  // Necessary, but not sure why?
  gpio.write(26, 1);
  // gpio.read(19);

  if (GPIOData.find().count() == 0) {
    GPIOData.insert( { pin: 19, values: [404] } );
  }
}

if (Meteor.isClient) {
  // toggle starts at 0 (off)
  Session.setDefault('toggle', 0);

  Template.hello.helpers({
    toggle: function () {
      return Session.get('toggle');
    },
    counter: function () {
      // Get GPIOData value
      var Data = GPIOData.findOne().values;
      return Data[Data.length - 1];

      // return Session.get('toggle');
    }
  });

  Template.hello.events({
    'click button': function () {
      // increment the counter when button is clicked
      if ( Session.get("toggle") == 0 ) {
        Session.set('toggle', 1);
      } else {
        Session.set('toggle', 0);
      }

      // Set GPIOData value on click
      gpio.write(26, Session.get('toggle') );

      // Check and update GPIOData value
      var ReadValue = gpio.read(19);
      if (ReadValue) {
        console.log("Updating GPIOData collection with " + ReadValue);
      } else {
        ReadValue = 4000004;
        console.log("Error: pin 19 is undefined");
      }

      GPIOData.update(
        GPIOData.findOne({pin: 19})._id, {
        $push: {
          values: ReadValue
        }
      });
    }
  });
}
```

``` HTML
<!-- helloworld.html -->
<head>
  <title>helloworld</title>
</head>

<body>
  <h1>Welcome to Meteor!</h1>

  {{> hello}}
</body>

<template name="hello">
  <button>Toggle Pin 26</button>

  <p>The current input should read: {{counter}}</p>
  <p>Your input pin = {{counter}}</p>
</template>
```

Code for raspberry pi:

``` shell
git clone https://github.com/tobetter/wiringPi
cd wiringPi
./build

gpio export 26 out
# gpio export 19 in # didn't help
```

**Comment by KyleKing** [comment]
I can't read pin 19? `gpio.read(19)` isn't working?

**Comment by SidPayton** [comment]
I also can't read any inputs. It would be nice, if @jantimon  could write a simple example on how to do it. The documentation just shows how to write outputs. Thank you very much
